REM Build Bat File
REM Precheck the Resource 
"C:\Program Files\MRE_SDK\tools\ResEditor\CmdShell.exe" save  "D:\MyGitHub\mre_md5\mre_md5.vcproj"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -fpic -g -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\MyGitHub\mre_md5\arm\gccmain.o" -c "C:\Program Files\MRE_SDK\lib\MRE30\src\gccmain.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE_SDK\include" -I "C:\Program Files\MRE_SDK\include\service" -I "D:\MyGitHub\mre_md5\include" -I "D:\MyGitHub\mre_md5\include\service" -I "D:\MyGitHub\mre_md5\include\component" -I "D:\MyGitHub\mre_md5\ResID" -I "D:\MyGitHub\mre_md5\src\app\widget" -I "D:\MyGitHub\mre_md5\src\app\launcher" -I "D:\MyGitHub\mre_md5\src\app\wallpaper" -I "D:\MyGitHub\mre_md5\src\app\screen_lock" -I "D:\MyGitHub\mre_md5\include\service" -I "D:\MyGitHub\mre_md5\include\component" -I "D:\MyGitHub\mre_md5\include\service" -I "D:\MyGitHub\mre_md5\src\framework" -I "D:\MyGitHub\mre_md5\src\framework\ui_core\base" -I "D:\MyGitHub\mre_md5\src\framework\ui_core\mvc" -I "D:\MyGitHub\mre_md5\src\framework\ui_core\pme" -I "D:\MyGitHub\mre_md5\src\framework\mmi_core" -I "D:\MyGitHub\mre_md5\src\ui_engine\vrt\interface" -I "D:\MyGitHub\mre_md5\src\component" -I "D:\MyGitHub\mre_md5\src\ui_engine\framework\xml" -I "D:\MyGitHub\mre_md5"
REM Copmile c file 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -c -fpic -g -mcpu=arm7tdmi-s -fvisibility=hidden -mthumb -mlittle-endian -O2 -D__MRE_COMPILER_GCC__ -fno-exceptions -fno-non-call-exceptions -o "D:\MyGitHub\mre_md5\arm\mre_md5.o" -c "d:\MyGitHub\mre_md5\mre_md5.c"      -D _MINIGUI_LIB_ -D _USE_MINIGUIENTRY -D _NOUNIX_ -D _FOR_WNC -D __MRE_SDK__ -D   __MRE_VENUS_NORMAL__  -D  __MMI_MAINLCD_240X320__ -I "C:\Program Files\MRE_SDK\include" -I "C:\Program Files\MRE_SDK\include\service" -I "D:\MyGitHub\mre_md5\include" -I "D:\MyGitHub\mre_md5\include\service" -I "D:\MyGitHub\mre_md5\include\component" -I "D:\MyGitHub\mre_md5\ResID" -I "D:\MyGitHub\mre_md5\src\app\widget" -I "D:\MyGitHub\mre_md5\src\app\launcher" -I "D:\MyGitHub\mre_md5\src\app\wallpaper" -I "D:\MyGitHub\mre_md5\src\app\screen_lock" -I "D:\MyGitHub\mre_md5\include\service" -I "D:\MyGitHub\mre_md5\include\component" -I "D:\MyGitHub\mre_md5\include\service" -I "D:\MyGitHub\mre_md5\src\framework" -I "D:\MyGitHub\mre_md5\src\framework\ui_core\base" -I "D:\MyGitHub\mre_md5\src\framework\ui_core\mvc" -I "D:\MyGitHub\mre_md5\src\framework\ui_core\pme" -I "D:\MyGitHub\mre_md5\src\framework\mmi_core" -I "D:\MyGitHub\mre_md5\src\ui_engine\vrt\interface" -I "D:\MyGitHub\mre_md5\src\component" -I "D:\MyGitHub\mre_md5\src\ui_engine\framework\xml" -I "D:\MyGitHub\mre_md5"
REM Link app 
"C:\Program Files (x86)\CodeSourcery\Sourcery_CodeBench_Lite_for_ARM_EABI\Bin\arm-none-eabi-gcc" -o "D:\MyGitHub\mre_md5\mre_md5.axf"  "D:\MyGitHub\mre_md5\arm\gccmain.o"  "D:\MyGitHub\mre_md5\arm\mre_md5.o" -fpic -msvr4-struct-return -pie  -T "C:\Program Files\MRE_SDK\lib\MRE30\armgcc\scat.ld" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\percommon.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\perfile.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\perpro.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\persysstorage.a" -l:"C:\Program Files\MRE_SDK\lib\MRE30\armgcc\persysfile.a"
REM Pack resource to app 
"C:\Program Files\MRE_SDK\tools\ResEditor\CmdShell.exe" pack -silent -resolution 240x320 -o "D:\MyGitHub\mre_md5\mre_md5.pkd" -e AXF "D:\MyGitHub\mre_md5\mre_md5.vcproj" "D:\MyGitHub\mre_md5\mre_md5.axf"
REM Add tag infromation 
"C:\Program Files\MRE_SDK\tools\PackDigist.exe" "D:\MyGitHub\mre_md5\mre_md5.vcproj" "mre_md5" "0.1.0" "RDZDX" "1500" "NotSupportBg" "Not Support rotate" "mre_md5" "mre_md5" "mre_md5" "9123456789123456" "content" " File ProMng SysStorage SysFile" "vxp" "GCC" "PKD" "UnCompress" "NoVPI" "Adaptable" "15728960" "UnSysMemAble" "
    " "-1" "UNPUSH" "-1" ""  "UnAutoStart"  "UnTransferImg" "NoIdleShortcut"  D:\MyGitHub\mre_md5\arm D:\MyGitHub\mre_md5\build.log

